version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ls
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 709861978753.dkr.ecr.ap-northeast-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cat app.py
      - docker build -t ai_text_process .
      - docker tag ai_text_process:latest 709861978753.dkr.ecr.ap-northeast-2.amazonaws.com/ai_text_process:latest
      - today=$(date "+%Y%m%d")
      - docker tag ai_text_process:latest 709861978753.dkr.ecr.ap-northeast-2.amazonaws.com/ai_text_process:$today
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 709861978753.dkr.ecr.ap-northeast-2.amazonaws.com/ai_text_process:latest
      - docker push 709861978753.dkr.ecr.ap-northeast-2.amazonaws.com/ai_text_process:$today
      - echo Deploy New Image to Lambda function...
      - aws lambda update-function-code --region ap-northeast-2 --function-name Ai-Text-Process-lambda --image-uri 709861978753.dkr.ecr.ap-northeast-2.amazonaws.com/ai_text_process:latest